language: python
sudo: false

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

notifications:
  email: false

before_install:
  - pip install -U pip

install: # Install packages
  - pip install numpy scipy virtualenv
  - pip install nose setuptools pep8 pyflakes coverage
  - pip install python-coveralls nose-cov
  - pip install profilehooks
  - python setup.py install

script: # Run test
  - pep8 nidata --exclude numpy_conversions,_external,example*,diffusion
  - pyflakes `find nidata -name \*.py | egrep -v nidata/core/_external | egrep -v example | egrep -v diffusion | egrep -v numpy_conversions`
  - nosetests --with-coverage --cover-package nidata

after_success: # Calculate coverage
  - coveralls
