language: python
sudo: false

python:
  - "2.7"
  - "3.5"

notifications:
  email: false

before_install:
  # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install: # Install packages
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy h5py scipy scikit-learn
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nose setuptools pep8 pyflakes coverage
  - "pip install python-coveralls nose-cov"
  - "pip install requests nilearn"  # so we can test HCP and Haxby datasets.
  - "pip install profilehooks"
  - python setup.py install

script: # Run test
  - pep8 nidata --exclude numpy_conversions,_external,example*,diffusion
  - pyflakes `find nidata -name \*.py | egrep -v nidata/core/_external | egrep -v example | egrep -v diffusion | egrep -v numpy_conversions`
  - nosetests --with-coverage --cover-package nidata

after_success: # Calculate coverage
  - coveralls
