language: python
sudo: false

python:
  - "2.7"
  - "3.5"

notifications:
  email: false

before_install:
  # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

install: # Install packages
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy nose
  # Coverage packages are on my binstar channel
  - "pip install python-coveralls coverage nose-cov"
  - "pip install profilehooks"
  - python setup.py install

script: # Run test
  - nosetests --with-coverage nidata

after_success: # Calculate coverage
  - coveralls --config_file .coveragerc
